#!/usr/bin/env python
# coding=utf8

import fontforge
from argparse import ArgumentParser

# Argparse
parser = ArgumentParser()
parser.add_argument("--version", help="Version")
parser.add_argument("--input", help="input file name")
parser.add_argument("--output", help="output file name")
parser.add_argument("--name", help="font name")
args = parser.parse_args()

# Open font instance
font = fontforge.open(args.input)
# Rename chaos
# TODO
font.fontname = "{}-Regular".format(args.name).replace(" ", "")
font.familyname = args.name
font.fullname = args.name
font.appendSFNTName("English (US)", "Preferred Family", args.name)
font.appendSFNTName("English (US)", "Compatible Full", args.name)
font.appendSFNTName("English (US)", "UniqueID",
                    "{} Nerd Font".format(args.name))
font.appendSFNTName("English (US)", "Trademark", "")

# The grave accent type is somehow not correctly detected;
# we want it to be an ordinary character
# From https://github.com/adam7/delugia-code
font["grave"].glyphclass = "baseglyph"

# Add Version Info
font.appendSFNTName("English (US)", "Version", args.version)
font.version = args.version

# Save Renamed font
font.generate(args.output)
