#!/usr/bin/env python
# coding=utf8

import fontforge
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument("--input", help="input file name")
parser.add_argument("--output", help="output file name")
args = parser.parse_args()
fontforge.open(args.input).generate(args.output)
