name: build
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Install FontForge
      run: |
        sudo add-apt-repository ppa:fontforge/fontforge -y -u
        sudo apt-get install --no-install-recommends --yes fontforge python-pip  python-configparser

    - name: Prepare
      run: make prepare

    - name: LS
      run: |
        ls -R vendor
        ls -R build

    - name: Build Cascadia Regular
      run: make cascadia-regular

    - name: Build Cascadia Regular [Windows]
      run: make cascadia-regular-win

    - name: Build Cascadia Italic
      run: make cascadia-italic

    - name: Build Cascadia Italic [Windows]
      run: make cascadia-italic-win

    - name: Build Cascadia Mono
      run: make cascadia-mono

    - name: Build Cascadia Mono [Windows]
      run: make cascadia-mono-win

    - name: Build Fantasque-Sans-Mono
      run: make fantasque

    - name: Build Fantasque-Sans-Mono [Windows]
      run: make fantasque-win

    - name: LS
      run: ls -R build

    # checksums
    - name: Generate checksums
      run: |
        make release-notes
        make checksums
        cat build/SHA256SUMS

    # Upload
    - name: Upload CascadiaCode
      uses: actions/upload-artifact@v2
      with:
        name:  CascadiaCode
        path: build/Cascadia/

    # Fantasque Sans Mono
    - name: Upload Fantasque-Sans-Mono
      uses: actions/upload-artifact@v2
      with:
        name:  Fantasque-Sans-Mono
        path: build/Fantasque/

    - name: Release
      if: startsWith(github.ref, 'refs/tags/v')
      run: ./scripts/release.sh
