name: build
on:
  push:
    branches:
      - master
      - stable
    paths-ignore:
      - ".gitignore"
      - ".editorconfig"
      - ".envrc"
      - "**.md"
      - ".vscode/**"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Install FontForge
      run: |
        sudo add-apt-repository ppa:fontforge/fontforge -y -u
        sudo apt-get install -y fontforge python-pip
        sudo -H pip install configparser

    - name: Prepare
      run: make prepare

    - name: Build Cascadia
      run: make cascadia

    - name: Build Cascadia [Windows]
      run: make cascadia-win

    - name: Build Fantasque-Sans-Mono
      run: make fantasque

    - name: Build Fantasque-Sans-Mono [Windows]
      run: make fantasque-win

    # checksums
    - name: Generate checksums
      run: |
        make release-notes
        make checksums
        cat build/SHA256SUMS

    # Upload
    - name: Upload CascadiaCode
      uses: actions/upload-artifact@v2
      with:
        name:  CascadiaCode
        path: build/Cascadia/

    # Fantasque Sans Mono
    - name: Upload Fantasque-Sans-Mono
      uses: actions/upload-artifact@v2
      with:
        name:  Fantasque-Sans-Mono
        path: build/Fantasque/
