name: build
on:
  push:
    branches:
      - master
      - stable
    paths-ignore:
      - ".gitignore"
      - ".editorconfig"
      - ".envrc"
      - "**.md"
      - ".vscode/**"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install FontForge
      run: |
        sudo add-apt-repository ppa:fontforge/fontforge -y -u
        sudo apt-get install -y fontforge python-pip
        sudo -H pip install configparser
    - name: Prepare
      run: make prepare
    - name: Build Patched fonts [Cascadia]
      run: make cascadia

    # checksums
    - name: Generate checksums
      run: |
        cd build
        sha256sum *.ttf > SHA256SUMS

    # Upload StarshipCascade
    - name: Upload StarshipCascade-Regular-NerdFont
      uses: actions/upload-artifact@v1
      with:
        name:  StarshipCascade-Regular-NerdFont
        path: build/StarshipCascade-Regular-NerdFont.ttf
    - name: Upload StarshipCascade-Mono-NerdFont
      uses: actions/upload-artifact@v1
      with:
        name: StarshipCascade-Mono-NerdFont
        path: build/StarshipCascade-Mono-NerdFont.ttf
    # Windows versions
    - name: Upload StarshipCascade-Regular-NerdFont-Windows
      uses: actions/upload-artifact@v1
      with:
        name:  StarshipCascade-Regular-NerdFont-Windows
        path: build/StarshipCascade-Regular-NerdFont-Windows.ttf
    - name: Upload StarshipCascade-Mono-NerdFont-Windows
      uses: actions/upload-artifact@v1
      with:
        name: StarshipCascade-Mono-NerdFont-Windows
        path: build/StarshipCascade-Mono-NerdFont-Windows.ttf
