name: build
on:
  push:
    branches:
      - master
      - stable
    paths-ignore:
      - ".gitignore"
      - ".editorconfig"
      - ".envrc"
      - "**.md"
      - ".vscode/**"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install FontForge
      run: |
        sudo add-apt-repository ppa:fontforge/fontforge -y -u
        sudo apt-get install -y fontforge python-pip
        sudo -H pip install configparser
    - name: Prepare
      run: make prepare
    - name: Build Patched fonts
      run: make cascadia
    - name: Build Patched fonts [Windows]
      run: make cascadia-win

    # checksums
    - name: Generate checksums
      run: |
        cd build
        sha256sum *.ttf > SHA256SUMS
        make release-notes

    # Upload StarshipCode
    - name: Upload StarshipCode
      uses: actions/upload-artifact@v1
      with:
        name:  StarshipCode
        path: build/StarshipCode.ttf
    - name: Upload StarshipMono
      uses: actions/upload-artifact@v1
      with:
        name: StarshipMono
        path: build/StarshipMono.ttf
    # Windows versions
    - name: Upload StarshipCode-Windows
      uses: actions/upload-artifact@v1
      with:
        name:  StarshipCode-Windows
        path: build/StarshipCode-Windows.ttf
    - name: Upload StarshipMono-Windows
      uses: actions/upload-artifact@v1
      with:
        name: StarshipMono-Windows
        path: build/StarshipMono-Windows.ttf
