name: build
on:
  push:
    branches:
      - master
      - stable
    paths-ignore:
      - ".gitignore"
      - ".editorconfig"
      - ".envrc"
      - "**.md"
      - ".vscode/**"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install FontForge
      run: |
        sudo add-apt-repository ppa:fontforge/fontforge -y -u
        sudo apt-get install -y fontforge python-pip
        sudo -H pip install configparser
    - name: Prepare
      run: make prepare
    - name: Build Patched fonts
      run: make fonts
    - name: Generate checksums
      run: |
        cd build
        sha256sum StarshipCode-Regular-NerdFont.ttf > SHA256SUMS
        sha256sum StarshipCode-Mono-NerdFont.ttf >> SHA256SUMS
    - uses: actions/upload-artifact@v1
      with:
        name: StarshipCode-Mono-NerdFont
        path: build/StarshipCode-Mono-NerdFont.ttf
    - uses: actions/upload-artifact@v1
      with:
        name: StarshipCode-Regular-NerdFont
        path: build/StarshipCode-Regular-NerdFont.ttf
    - uses: actions/upload-artifact@v1
      with:
        name: SHA256SUMS
        path: build/SHA256SUMS