name: build
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: |
          sudo apt-get install \
            --no-install-recommends \
            --yes \
              fontforge \
              python3-fontforge \
              python3-coloredlogs

      - name: Build CascadiaCode Regular
        run: make cascadiacode-regular

      - name: Build CascadiaCode Italic
        run: make cascadiacode-italic

      - name: Build CascadiaMono Regular
        run: make cascadiamono-regular

      - name: Build CascadiaMono Italic
        run: make cascadiamono-italic

      - name: Build FantasqueSansMono Regular
        run: make fantasque-regular

      - name: Build FantasqueSansMono Italic
        run: make fantasque-italic

      - name: Build Ubuntu Regular
        run: make ubuntu-regular

      - name: Build Ubuntu Italic
        run: make ubuntu-regular-italic

      - name: Build UbuntuMono Regular
        run: make ubuntumono-regular

      - name: Build UbuntuMono Italic
        run: make ubuntumono-regular-italic

      - name: Generate checksums and release notes
        run: |
          make release-notes
          make checksums

      - name: LS
        run: ls -R build

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: build/
          name: patched-fonts

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          path: build
          name: patched-fonts

      - name: Release
        run: |
          gh release create \
            --title "$CURRENT_VERSION" \
            --latest \
            --notes-file build/release-notes.md \
            "$CURRENT_VERSION" \
            build/SHA256SUMS.txt \
            build/Cascadia/*.ttf \
            build/FantasqueSans/*.ttf \
            build/Ubuntu/*.ttf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURRENT_VERSION: ${{ github.ref_name }}
