name: build
on:
  push:
    branches:
      - master
      - stable
    paths-ignore:
      - ".gitignore"
      - ".editorconfig"
      - ".envrc"
      - "**.md"
      - ".vscode/**"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install FontForge
      run: |
        sudo add-apt-repository ppa:fontforge/fontforge -y -u
        sudo apt-get install -y fontforge python-pip
        sudo -H pip install configparser
    - name: Prepare
      run: make prepare
    - name: Build Patched fonts
      run: make cascadia
    - name: Build Patched fonts [Windows]
      run: make cascadia-win

    # checksums
    - name: Generate checksums
      run: |
        make release-notes
        cd build
        sha256sum *.ttf > SHA256SUMS

    # Upload Starship
    - name: Upload StarshipFonts
      uses: actions/upload-artifact@v1
      with:
        name:  StarshipFonts
        path: |
          build/StarshipCode.ttf
          build/StarshipMono.ttf

    # Windows versions
    - name: Upload Starship-Windows
      uses: actions/upload-artifact@v1
      with:
        name:  Starship-Windows
        path: |
          build/StarshipCode-Windows.ttf
          build/StarshipMono-Windows.ttf
