name: release
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install FontForge
      run: |
        sudo add-apt-repository ppa:fontforge/fontforge -y -u
        sudo apt-get install -y fontforge python-pip
        sudo -H pip install configparser
    - name: Prepare
      run: make prepare

    - name: Build Patched fonts [Cascadia]
      run: make cascadia

    - name: Generate checksums
      run: |
        make release-notes
        cd build
        sha256sum *.ttf > SHA256SUMS
    # Because github action's way of referencing commits and tags sucks
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    # create a release on tag
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Starship ${{ steps.get_version.outputs.VERSION }}
        body_path: build/release-notes.md
        draft: false
        prerelease: false

    # Upload Release assets
    - name: Upload Regular Font [Cascadia]
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/StarshipCascade-Regular-NerdFont.ttf
        asset_name: StarshipCascade-Regular-NerdFont.ttf
        asset_content_type: font/ttf

    - name: Upload Mono Font [Cascadia]
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/StarshipCascade-Mono-NerdFont.ttf
        asset_name: StarshipCascade-Mono-NerdFont.ttf
        asset_content_type: font/ttf

    - name: Upload Regular Font [Cascadia-Windows]
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/StarshipCascade-Regular-NerdFont-Windows.ttf
        asset_name: StarshipCascade-Regular-NerdFont-Windows.ttf
        asset_content_type: font/ttf

    - name: Upload Mono Font [Cascadia-Windows]
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/StarshipCascade-Mono-NerdFont-Windows.ttf
        asset_name: StarshipCascade-Mono-NerdFont-Windows.ttf
        asset_content_type: font/ttf

    - name: Upload Checksums
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/SHA256SUMS
        asset_name: SHA256SUMS
        asset_content_type: text/plain
